[package]
name = "tracing-capture"
version = "0.1.0"
edition = "2021"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Tracing infrastructure for Tardigrade workflows"
repository = "https://github.com/slowli/tracing-toolbox"

[dependencies]
predicates = { version = "2.1.1", default-features = false }
tracing-core = "0.1.30"

tracing-tunnel = { version = "0.1.0", path = "../tunnel" }

[dependencies.tracing-subscriber]
version = "0.3.16"
default-features = false
features = ["std"]

[dev-dependencies]
assert_matches = "1.5.0"
doc-comment = "0.3.3"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["registry", "fmt"] }
version-sync = "0.9.4"

tracing-tunnel = { version = "0.1.0", path = "../tunnel", features = ["sender", "receiver"] }
