[package]
name = "tardigrade-tracing"
version = "0.1.0"
edition = "2021"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["orchestration", "workflow", "business process"]
categories = ["asynchronous", "wasm"]
description = "Tracing infrastructure for Tardigrade orchestration engine"
repository = "https://github.com/slowli/tardigrade"

[dependencies]
once_cell = "1.15.0"
serde = { version = "1", features = ["derive"] }
tracing-core = "0.1.30"

[dependencies.tracing-subscriber]
version = "0.3.16"
optional = true
default-features = false
features = ["std"]

[dev-dependencies]
assert_matches = "1.5.0"
insta = { version = "1.21.0", features = ["yaml"] }
serde_json = "1"
tracing = "0.1.37"

[features]
default = []
# Enables `EmittingSubscriber`.
subscriber = []
# Enables `EventConsumer`.
consumer = []
# Enables capturing tracing information.
capture = ["tracing-subscriber"]

[[test]]
name = "integration"
path = "tests/integration.rs"
required-features = ["subscriber", "consumer", "capture"]
